# Generated by Django 3.1.5 on 2022-09-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneday_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oneday_user',
            options={'verbose_name': '하루한줄 사용자', 'verbose_name_plural': '하루한줄 사용자'},
        ),
        migrations.AddField(
            model_name='oneday_user',
            name='useremail',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
